id: I9D7D45E8
ocr_import_info:
  timestamp: '2023-06-24T05:32:13.357408+00:00'
  batch_id: batch-6feb
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: PechaJobs
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-06-24 05:50:30.582282+00:00
last_modified: 2023-06-24 05:50:30.582288+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1NLM2855
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1NLM2855
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བསྟན་བཅོས་བཞི་བརྒྱ་པ་ཞེས་བྱ་བའི་ཚིག་ལེའུར་བྱས་པ།
  languages:
  - bo
  author: སློབ་དཔོན་འཕགས་པ་ལྷ།
statistics:
  ocr_word_mean_confidence_index: 0.9182731332866981
  ocr_word_median_confidence_index: 0.97566724
bases:
  I1NLM2855_001:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1NLM2855_001
      total_pages: 572
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1NLM2855_001.txt
    statistics:
      ocr_word_median_confidence_index: 0.97566724
      ocr_word_mean_confidence_index: 0.9182731332866981
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
